### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by Gerrit0** [vamship/build-utils#1]
In `directory.js` `_path.sep` is used to construct a regular expression. This doesn't work on Windows since it evaluates to `new RegExp('\\', 'g')` and throws.

https://github.com/vamship/build-utils/blob/50e640187bad3261c090197aab821e9a169d49ad/src/directory.js#L5

**Comment by vamship** [comment]
Thank you for pointing this out. This issue has been fixed with release 0.0.15.
